=== AlexandreRousselle/NAW/TP1/ex2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT recette (nom, portion, preparation, cuisson, repos?, ingredients, guide)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT portion (#PCDATA)>
<!ELEMENT preparation EMPTY>
<!ELEMENT cuisson EMPTY>
<!ELEMENT repos EMPTY>
<!ELEMENT ingredients (i)*>
<!ELEMENT i (nomingredient, (nbre | poids))>
<!ELEMENT nomingredient (#PCDATA)>
<!ELEMENT nbre (#PCDATA)>
<!ELEMENT poids (#PCDATA)>
<!ELEMENT guide (block)*>
<!ELEMENT block (#PCDATA | renvoi | cuisson | repos | strong)*>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT renvoi (#PCDATA)>
<!ATTLIST preparation value CDATA #REQUIRED unit (sec|min|h) #REQUIRED>
<!ATTLIST cuisson value CDATA #REQUIRED unit (sec|min|h) #REQUIRED>
<!ATTLIST repos value CDATA #REQUIRED unit (sec|min|h) #REQUIRED>
<!ATTLIST nomingredient id CDATA #REQUIRED>
<!ATTLIST poids unit (gramme|kilogramme) #REQUIRED>
<!ATTLIST renvoi ref CDATA #REQUIRED>

=== AlexandreRousselle/NAW/TP1/recette1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE recette SYSTEM "ex2.dtd">
<recette>
	<nom>Tiramisu</nom>
	<portion>6/8</portion>
	<preparation value="35" unit="min"/>
	<cuisson value="0" unit="min"/>
	<repos value="12" unit="h"/>
	<ingredients>
		<i>
			<nomingredient id="ing1">oeufs</nomingredient>
			<nbre>5</nbre>
		</i>
		<i>
			<nomingredient id="ing2">sucre en poudre</nomingredient>
			<poids unit="gramme">100</poids>
		</i>
		<i>
			<nomingredient id="ing3">mascarpone</nomingredient>
			<poids unit="gramme">500</poids>
		</i>
		<i>
			<nomingredient id="ing4">cafe soluble</nomingredient>
			<poids unit="gramme">25</poids>
		</i>
		<i>
			<nomingredient id="ing5">biscuits `a la cuill`ere</nomingredient>
			<nbre>42</nbre>
		</i>
		<i>
			<nomingredient id="ing6">cacao non sucr안</nomingredient>
			<poids unit="gramme">10</poids>
		</i>
	</ingredients>
	<guide>
		<block>Commencez par s안parer les 5 jaunes d_<renvoi ref="ing1">oeufs</renvoi> de leur blanc dans deux grands saladiers et montez les 5 blancs d_<renvoi ref="ing1">oeufs</renvoi> en neige tr`es fermes.</block>
		<block>Battez les 5 jaunes avec le <renvoi ref="ing2">sucre</renvoi> jusqu_`a l_obtention d_un m안lange mousseux, puis ajoutez-y le <renvoi ref="ing3">mascarpone</renvoi>.</block>
		<block>Incorporez `a pr안sent les blancs d_oeufs dans le m안lange.</block>
		<block>Pr안parez un caf안 bien fort avec du <renvoi ref="ing4">caf안 soluble</renvoi> et trempez-y les <renvoi ref="ing5">biscuits</renvoi> au fur et `a mesure de leur installation dans le plat. <strong>Attention les biscuits absorbent tr`es vite le caf안.</strong>
		</block>
		<block>Commencez par disposer une couche de biscuits imbib안s au fond du moule, puis versez une couche de m안lange et ainsi de suite.</block>
		<block>Saupoudrez le cacao sur le tiramisu en utilisant une petite passoire. Il sera ainsi plus facile de le parsemer uniform안ment.</block>
		<block>Il ne vous reste plus qu_`a le placer au r안frig안rateur durant <repos value="12" unit="h"/> heures.</block>
	</guide>
</recette>
